permissionsetextension 96960 "OD AM Admin Ext" extends "ODPM ADMIN"
{
    Permissions =
        table "OD AM Asset Structure Buffer" = X,
        tabledata "OD AM Asset Structure Buffer" = RIMD,
        table "OD AM Asset Create Req." = X,
        tabledata "OD AM Asset Create Req." = RIMD,
        table "OD AM Asset Import" = X,
        tabledata "OD AM Asset Import" = RIMD,
        table "OD Lease Contract Import" = X,
        tabledata "OD Lease Contract Import" = RIMD,
        table "OD AM Lease Contract Unit" = X,
        tabledata "OD AM Lease Contract Unit" = RIMD,
        table "OD AM Occupancy Buffer" = X,
        tabledata "OD AM Occupancy Buffer" = RIMD,
        page "OD AM Asset Structure" = X,
        page "OD AM Asset List" = X,
        page "OD AM Asset Import List" = X,
        page "OD Lease Contract Import List" = X,
        page "OD AM Property Asset FactBox" = X,
        page "OD AM New Asset" = X,
        page "OD AM Lease Contract Units" = X,
        page "OD AM Contract Asset FactBox" = X,
        page "OD AM Lease Contract Card" = X,
        page "OD AM Lease Contract List" = X,
        page "OD AM Occupancy View" = X,
        page "OD AM Asset Availability" = X,
        codeunit "OD AM Asset Structure Mgt." = X,
        codeunit "OD AM Asset Import Mgt." = X,
        codeunit "OD AM FA Buffer Mgt." = X,
        codeunit "OD Lease Contract Import Mgt." = X,
        codeunit "OD AM Contract Asset Mgt." = X,
        codeunit "OD AM Contract Unit Upgrade" = X,
        codeunit "OD AM Occupancy Mgt." = X,
        codeunit "OD AM FA to FRE Mgt." = X;
}
